name: "Automerge wiki updates to main"

on:
  push:
    branches:
      - 'automerge'
    paths:
      - 'docs/**'

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Merge Pull Request
        uses: reitermarkus/automerge@v2.6.0
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
