name: Wiki sync

on:
  push:
    branches:
      - automerge
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  GIT_AUTHOR_NAME: "Russell Yazbeck"
  GIT_AUTHOR_EMAIL: "russellyazbeck@gmail.com"

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }} # allows us to push back to repo
          ref: automerge
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: docs
          destination: wiki
          token: ${{ env.GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }} # allows us to push back to repo
          ref: automerge
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: docs
          token: ${{ env.GITHUB_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: automerge
          
  automerge:
    name: "Automerge wiki updates to main"
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Merge Pull Request
        uses: reitermarkus/automerge@v2.6.0
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
